name: 'fiction_bank'
version: '1.0.0'

profile: 'fiction_bank'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fiction_bank:
    staging:
      +materialized: view
    marts:
      +materialized: table
